//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_detail
    {
        public int Id { get; set; }
        public Nullable<int> Pro_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Order_id { get; set; }
    }
}
